# Generated by Django 6.0.1 on 2026-02-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="domain",
            field=models.CharField(default="---", max_length=128),
            preserve_default=False,
        ),
    ]
