# Generated by Django 6.0.1 on 2026-01-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_comment_client_issue_client_project_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="client",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="client",
        ),
        migrations.RemoveField(
            model_name="project",
            name="client",
        ),
    ]
