# Generated by Django 6.0.1 on 2026-01-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0004_remove_comment_client_remove_issue_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
