# Generated by Django 6.0.1 on 2026-02-05 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0007_issue_unique_issue_name_per_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.UniqueConstraint(
                fields=("description", "issue"), name="unique_comment_name_per_issue"
            ),
        ),
    ]
