# Generated by Django 6.0.1 on 2026-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_data_be_collected",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_birth",
            field=models.DateField(verbose_name="Date de naissance"),
        ),
    ]
