# Generated by Django 6.0.1 on 2026-01-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_can_be_contacted_and_more"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="client.client",
            ),
            preserve_default=False,
        ),
    ]
