# Generated by Django 6.0.1 on 2026-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_data_be_collected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(default=False),
        ),
    ]
