# Generated by Django 6.0.1 on 2026-02-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_can_be_contacted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="domain",
            field=models.CharField(default="---", max_length=128),
            preserve_default=False,
        ),
    ]
