# Generated by Django 6.0.1 on 2026-02-11 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="domain",
        ),
    ]
